### ISSUE TITLE
Require node 12 or greater

### ISSUE THREAD

**Issue by meryllblanchet** [adobe/aio-cli-plugin-certificate#18]
### Expected Behaviour

https://github.com/adobe/aio-cli/blob/08721fa0f1c257f0f79e8a270dd5f8fd707a2bf3/package.json#L56

### Actual Behaviour

https://github.com/adobe/aio-cli-plugin-certificate/blob/41a0fe148b63866873326bde84deaf8d45191944/package.json#L33

**Comment by purplecabbage** [comment]
done
